# Generated by Django 5.1.6 on 2025-02-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommodel',
            name='type',
            field=models.CharField(choices=[('dialog', 'Dialog'), ('group', 'GroupChat')], default='group', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participantmodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.chatroommodel'),
        ),
    ]
